import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform;

/// Firebase configuration for the THENIJOBS project.
///
/// This connects to the SAME Firebase project as the web app: thenijobs-9f01d
///
/// IMPORTANT: Replace these with values from your google-services.json
/// generated by running: flutterfire configure
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        return web;
    }
  }

  /// Web configuration (same as the Next.js app)
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAXHgdvKXi4pFPNGciMbZE8lPITN9Hsug',
    authDomain: 'thenijobs-9f01d.firebaseapp.com',
    projectId: 'thenijobs-9f01d',
    storageBucket: 'thenijobs-9f01d.firebasestorage.app',
    messagingSenderId: '1057136000588',
    appId: '1:1057136000588:web:12506f87f1f502596a7ee9',
    measurementId: 'G-T21WC74YFY',
    databaseURL: 'https://thenijobs-9f01d-default-rtdb.firebaseio.com',
  );

  /// Android configuration
  /// TODO: After adding an Android app in Firebase Console,
  ///       download google-services.json and run `flutterfire configure`
  ///       to auto-generate these values.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAXHgdvKXi4pFPNGciMbZE8lPITN9Hsug',
    projectId: 'thenijobs-9f01d',
    storageBucket: 'thenijobs-9f01d.firebasestorage.app',
    messagingSenderId: '1057136000588',
    appId: '1:1057136000588:android:REPLACE_WITH_ANDROID_APP_ID',
    databaseURL: 'https://thenijobs-9f01d-default-rtdb.firebaseio.com',
  );

  /// iOS configuration (if needed in future)
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAXHgdvKXi4pFPNGciMbZE8lPITN9Hsug',
    projectId: 'thenijobs-9f01d',
    storageBucket: 'thenijobs-9f01d.firebasestorage.app',
    messagingSenderId: '1057136000588',
    appId: '1:1057136000588:ios:REPLACE_WITH_IOS_APP_ID',
    iosBundleId: 'com.thenijobs.app',
    databaseURL: 'https://thenijobs-9f01d-default-rtdb.firebaseio.com',
  );
}
