import 'package:firebase_auth/firebase_auth.dart' as firebase_auth;
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:google_sign_in/google_sign_in.dart';
import 'package:dio/dio.dart';
import 'package:thenijobs/models/user.dart';
import 'package:thenijobs/config/constants.dart';

class AuthService {
  final firebase_auth.FirebaseAuth _firebaseAuth = firebase_auth.FirebaseAuth.instance;
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;
  final GoogleSignIn _googleSignIn = GoogleSignIn();
  final Dio _dio = Dio(BaseOptions(baseUrl: apiBaseUrl));

  Stream<AppUser?> get authStateChanges {
    return _firebaseAuth.authStateChanges().asyncMap((firebaseUser) async {
      if (firebaseUser == null) return null;

      // Fetch user profile from Firestore users collection
      final docSnap = await _firestore.collection('users').doc(firebaseUser.uid).get();
      if (!docSnap.exists) {
        // Return a basic AppUser if document doesn't exist yet (e.g. during onboarding)
        return AppUser(
          uid: firebaseUser.uid,
          email: firebaseUser.email ?? '',
          displayName: firebaseUser.displayName ?? '',
          role: UserRole.jobSeeker,
          createdAt: DateTime.now(),
          updatedAt: DateTime.now(),
        );
      }
      return AppUser.fromMap(docSnap.data()!, docSnap.id);
    });
  }

  Future<void> signInWithEmail(String email, String password) async {
    await _firebaseAuth.signInWithEmailAndPassword(email: email, password: password);
  }

  Future<void> registerWithEmail({
    required String email,
    required String password,
    required String displayName,
    required UserRole role,
  }) async {
    final credentials = await _firebaseAuth.createUserWithEmailAndPassword(
      email: email,
      password: password,
    );

    final uid = credentials.user!.uid;
    final now = DateTime.now();

    final user = AppUser(
      uid: uid,
      email: email,
      displayName: displayName,
      role: role,
      createdAt: now,
      updatedAt: now,
      setupCompleted: false,
    );

    // Save to Firestore
    await _firestore.collection('users').doc(uid).set(user.toMap());
  }

  Future<void> sendOtp(String phoneNumber) async {
    try {
      final response = await _dio.post('/api/otp/send', data: {
        'phone': phoneNumber,
      });
      if (response.statusCode != 200) {
        throw Exception(response.data['error'] ?? 'Failed to send OTP');
      }
    } catch (e) {
      throw Exception('OTP Send Error: $e');
    }
  }

  Future<void> verifyOtpAndSignIn(String phoneNumber, String code) async {
    try {
      final response = await _dio.post('/api/otp/verify', data: {
        'phone': phoneNumber,
        'code': code,
      });

      if (response.statusCode == 200 && response.data['token'] != null) {
        final customToken = response.data['token'] as String;
        // Sign in to Firebase with custom token generated by the server
        await _firebaseAuth.signInWithCustomToken(customToken);
      } else {
        throw Exception(response.data['error'] ?? 'Verification failed');
      }
    } catch (e) {
      throw Exception('OTP Verification Error: $e');
    }
  }

  Future<void> signInWithGoogle() async {
    final GoogleSignInAccount? googleUser = await _googleSignIn.signIn();
    if (googleUser == null) return;

    final GoogleSignInAuthentication googleAuth = await googleUser.authentication;
    final credential = firebase_auth.GoogleAuthProvider.credential(
      accessToken: googleAuth.accessToken,
      idToken: googleAuth.idToken,
    );

    final userCredential = await _firebaseAuth.signInWithCredential(credential);
    final uid = userCredential.user!.uid;

    // Check if user already has a document in the users collection
    final docSnap = await _firestore.collection('users').doc(uid).get();
    if (!docSnap.exists) {
      final now = DateTime.now();
      final user = AppUser(
        uid: uid,
        email: googleUser.email,
        displayName: googleUser.displayName ?? '',
        photoURL: googleUser.photoUrl,
        role: UserRole.jobSeeker, // Default role
        createdAt: now,
        updatedAt: now,
        setupCompleted: false,
      );
      await _firestore.collection('users').doc(uid).set(user.toMap());
    }
  }

  Future<void> signOut() async {
    await _googleSignIn.signOut();
    await _firebaseAuth.signOut();
  }
}
